apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-backend
  namespace: smart-hr
  labels:
    app: hr-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-backend
  template:
    metadata:
      labels:
        app: hr-backend
    spec:
      containers:
      - name: hr-backend
        image: nikhil2202/hr-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/hrdb"
---
apiVersion: v1
kind: Service
metadata:
  name: hr-backend-service
  namespace: smart-hr
spec:
  type: NodePort
  selector:
    app: hr-backend
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30096
