apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-frontend
  labels:
    app: hr-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-frontend
  template:
    metadata:
      labels:
        app: hr-frontend
    spec:
      containers:
      - name: hr-frontend
        image: <YOUR_DOCKERHUB>/hr-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://hr-backend-service:4000"
---
apiVersion: v1
kind: Service
metadata:
  name: hr-frontend-service
spec:
  selector:
    app: hr-frontend
  ports:
    - name: frontend
      port: 80              # service port
      targetPort: 3000      # container port
      nodePort: 30080       # public port
  type: NodePort
