apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-frontend
  namespace: smart-hr
  labels:
    app: hr-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-frontend
  template:
    metadata:
      labels:
        app: hr-frontend
    spec:
      containers:
      - name: hr-frontend
        image: nikhil2202/hr-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://hr-backend-service:4000"
---
apiVersion: v1
kind: Service
metadata:
  name: hr-frontend-service
  namespace: smart-hr
spec:
  type: NodePort
  selector:
    app: hr-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30097
